# Generated by Django 2.2.7 on 2019-11-09 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailsModal',
            fields=[
                ('p_no', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100, unique=True)),
                ('p_price', models.IntegerField()),
                ('p_quantity', models.IntegerField()),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.MerchantModal')),
            ],
        ),
    ]
