# Generated by Django 2.2.7 on 2019-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerDetailsModel',
            fields=[
                ('consumer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('consumer_name', models.CharField(max_length=30)),
                ('consumer_contact_no', models.IntegerField(unique=True)),
                ('consumer_email', models.EmailField(max_length=254, unique=True)),
                ('consumer_password', models.CharField(max_length=10)),
                ('consumer_address', models.TextField()),
                ('consumer_status', models.CharField(max_length=10)),
            ],
        ),
    ]
